# Start from the official Airflow image
# We specify a Python version to ensure consistency
FROM apache/airflow:2.8.0-python3.11

# 1. Switch to root to perform system-level installs
USER root

# 'build-essential' is needed in case some Python libs need to compile C code
RUN apt-get update && \
    apt-get install -y build-essential && \
    # Clean up apt cache to save space
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 2. Switch back to the airflow user so the app runs securely
USER airflow

# OPTIMIZATION: Install CPU-only PyTorch first.
# This saves GBs of space because it skips the CUDA (GPU) drivers.
# Weaviate/Ollama will handle the heavy lifting, so CPU embeddings are fine here.
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir "numpy==1.26.4"

# Install the rest of the libraries
RUN pip install --no-cache-dir \
    "apache-airflow-providers-postgres" \
    "apache-airflow-providers-docker" \
    "langchain" \
    "langchain-community" \
    "sentence-transformers" \
    "weaviate-client" \
    "minio" \
    "beautifulsoup4" \
    "requests" \
    "ollama"

# Note: We add 'ollama' here so the Airflow DAG can
# use the Python client to talk to your host API